package com.jshelf.themoviebookingapp.utils

const val BASE_URL = "https://tmba.padc.com.mm"   //base url
const val MOVIE_LIST_BASE_URL = "https://api.themoviedb.org"
const val MOVIE_API_KEY = "5d947500db5e8c0be328ff71dcf7b0b9"
const val IMAGE_BASE_URL = "https://image.tmdb.org/t/p/w400/"
const val IMAGE_BASE_URL_300 = "https://image.tmdb.org/t/p/w300/"
const val API_GET_NOW_PLAYING = "/3/movie/now_playing"
const val API_REGISTER_WITH_EMAIL = "/api/v1/register" //end point
const val API_GET_PROFILE = "/api/v1/profile"
const val API_LOGIN_WITH_EMAIL = "/api/v1/email-login"
const val API_LOGOUT = "/api/v1/logout"
const val API_GET_UPCOMING = "/3/movie/upcoming"
const val API_GET_MOVIE_DETAIL = "/3/movie"
const val API_GET_CREDIT_BY_MOVIE = "/3/movie"
const val API_GET_CINEMA_DAY_TIMESLOT = "/api/v1/cinema-day-timeslots"
const val API_GET_MOVIE_SEAT = "/api/v1/seat-plan"
const val API_GET_SNACK_LIST = "/api/v1/snacks"
const val API_GET_PAYMENT_METHOD_LIST = "/api/v1/payment-methods"
const val API_CREATE_CARD="/api/v1/card"
const val API_CHECK_OUT="/api/v1/checkout"
const val API_JSON="Content-Type: application/json"
const val BEARER_TOKEN="Bearer "

const val FIELD_NAME = "name"
const val FIELD_EMAIL = "email"
const val FIELD_PHONE = "phone"
const val FIELD_PASSWORD = "password"
const val PARAM_AUTHORIZATION = "Authorization"
const val PARAM_API_KEY = "api_key"
const val PARAM_PAGE = "page"
const val PARAM_MOVIE_ID = "movie_id"
const val PARAM_DATE = "date"
const val PARAM_SELECTED_DATE = "booking_date"
const val PARAM_CINEMA_TIME_SLOT_ID = "cinema_day_timeslot_id"
const val PARAM_CARD_HOLDER="card_holder"
const val PARAM_CARD_NUMBER="card_number"
const val PARAM_EXPIRE_DATE="expiration_date"
const val PARAM_CVC="cvc"


const val PARAM_ACCESS_TOKEN="access-token"
const val FIELD_GOOGLE_ACCESS_TOKEN="google-access-token"